apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: local-storage
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - 52-54-00-2b-4e-ed
  storageClassDevices:
    - storageClassName: local-storage
      volumeMode: Filesystem
      fsType: xfs
      devicePaths:
        - /dev/sdb
