apiVersion: v1
kind: Pod
metadata:
  name: lvm-test
  namespace: default
spec:
  containers:
    - name: app
      image: registry.access.redhat.com/ubi9/ubi
      command:
        - /bin/bash
        - -c
        - |
          echo "Application restored and running"
          sleep infinity
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: lvm-test-pvc
